### ISSUE TITLE
Cuisine-Contributor table in README is wrongly written

### ISSUE THREAD

**Issue by GToidZ** [mjrchy/KU-international-cafe#16]
https://github.com/mjrchy/KU-international-cafe/blob/e733ac95babb37076133d550ceb824d79fcce1b1/README.md?plain=1#L7-L9

* Should your name be in the Cuisine column?
* Your cuisine entries should link to each section in `menu.md`

**Comment by ReggieReo** [comment]
Fix this in 78fd19f26798a0652452fc8704ef94993f7def7a, thank you.
