### ISSUE TITLE
Hyperlink doesn't work

### ISSUE THREAD

**Issue by Savetang19** [mjrchy/KU-international-cafe#23]
https://github.com/mjrchy/KU-international-cafe/blob/144a64a04244e2f93ea223ef1127d37ef596402a/menu.md?plain=1#L2

Hyperlink for `Japanese Food` section does not work.

**Comment by jbrucker** [comment]
Good one.
PR review should be more thorough (its visually obvious that this link is invalid).

**Comment by ReggieReo** [comment]
Fix this in c286afaf48858ab5e0d7b2869fc7042959c2f7b3, and 99c9971e7217a7e9ddc147e3279ef8a1188ab613, Thank you.
